import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import Providers from "./Provider";

export const metadata: Metadata = {
  title: "Homemade Ukadiche Modak Besan ladoo - Swad Gharana",
  description:
    "Welcome to our online sweet shop offering traditional Indian sweets...",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <head>
      <link rel="shortcut icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
    </head>
    <body>
      {/* The AppRouterCacheProvider component is responsible for collecting the CSS generated by MUI System on the server, as Next.js is streaming 
        chunks of the .html page to the client. While it's not required to use the AppRouterCacheProvider component, 
        it's recommended to use it to ensure that the styles are appended to the <head> and not rendering in the <body>.  */}
      <AppRouterCacheProvider>
        <Providers>{children}</Providers>
      </AppRouterCacheProvider>
    </body>
  </html>
);

export default RootLayout;
